# Generated by Django 2.0.2 on 2018-05-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAttribute',
            fields=[
                ('e_ano', models.IntegerField(db_column='E_ano', primary_key=True, serialize=False)),
                ('e_aname', models.CharField(blank=True, db_column='E_aname', max_length=20, null=True)),
            ],
            options={
                'db_table': 'equipment_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSet',
            fields=[
                ('s_no', models.AutoField(db_column='S_no', primary_key=True, serialize=False)),
                ('s_name', models.CharField(db_column='s_name', max_length=20)),
            ],
            options={
                'db_table': 'equipment_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSkill',
            fields=[
                ('sk_no', models.IntegerField(db_column='Sk_no', primary_key=True, serialize=False)),
                ('sk_type', models.CharField(db_column='Sk_type', max_length=20)),
                ('sk_name', models.CharField(blank=True, db_column='Sk_name', max_length=40, null=True)),
                ('sk_describe', models.CharField(blank=True, db_column='Sk_describe', max_length=400, null=True)),
            ],
            options={
                'db_table': 'equipment_skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSynthesis',
            fields=[
                ('SYN_no', models.IntegerField(db_column='SYN_no', primary_key=True, serialize=False)),
                ('e_num', models.IntegerField(db_column='E_num')),
            ],
            options={
                'db_table': 'equipment_synthesis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentTAttri',
            fields=[
                ('TA_no', models.IntegerField(db_column='TA_no', primary_key=True, serialize=False)),
                ('e_adata', models.CharField(blank=True, db_column='E_adata', max_length=20, null=True)),
            ],
            options={
                'db_table': 'equipment_t_attri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentTotal',
            fields=[
                ('e_no', models.IntegerField(db_column='E_no', primary_key=True, serialize=False)),
                ('e_name', models.CharField(blank=True, db_column='E_name', max_length=20, null=True)),
                ('e_type', models.CharField(blank=True, db_column='E_type', max_length=10, null=True)),
                ('e_price', models.IntegerField(blank=True, db_column='E_price', null=True)),
                ('e_tprice', models.IntegerField(blank=True, db_column='E_tprice', null=True)),
                ('e_pic', models.CharField(blank=True, db_column='E_pic', max_length=200, null=True)),
            ],
            options={
                'db_table': 'equipment_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentTSk',
            fields=[
                ('TSK_no', models.IntegerField(db_column='TSK_no', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'equipment_t_sk',
                'managed': False,
            },
        ),
    ]
